# Generated by Django 2.2.4 on 2021-03-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_ids',
            field=models.IntegerField(),
        ),
    ]
