# Generated by Django 2.2.4 on 2021-03-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold_by',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='bought_by',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='product_sold',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='sold_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
