# Generated by Django 2.2.4 on 2021-03-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_auto_20210304_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_ids',
            new_name='product_id',
        ),
    ]
