# Generated by Django 2.2.4 on 2021-03-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_auto_20210304_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, default='no-product-image.png', upload_to='static/images/products/'),
        ),
    ]
