# Generated by Django 2.2.4 on 2021-03-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_auto_20210304_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(default='no-product-image.png', upload_to='static/images/products'),
        ),
    ]
