# Generated by Django 2.2.4 on 2021-03-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_auto_20210304_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='in-process', max_length=10),
        ),
    ]
