# Generated by Django 2.2.4 on 2021-03-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_auto_20210306_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='no-product-image.png', upload_to='products_img/'),
        ),
    ]
