# Generated by Django 2.2.4 on 2021-03-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_auto_20210306_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bill_addr',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ship_addr',
        ),
    ]
