# Generated by Django 2.2.4 on 2021-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_auto_20210314_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_addr',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
